// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChessAction.proto

package se.kth.cnlib.protobuf;

public final class ChessActionOuterClass {
  private ChessActionOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChessActionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ChessAction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Standard algebraic chess notation
     * </pre>
     *
     * <code>string move = 1;</code>
     */
    java.lang.String getMove();
    /**
     * <pre>
     * Standard algebraic chess notation
     * </pre>
     *
     * <code>string move = 1;</code>
     */
    com.google.protobuf.ByteString
        getMoveBytes();

    /**
     * <pre>
     * General info that could be nice to send. e.g. on error, send why.
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    java.lang.String getMessage();
    /**
     * <pre>
     * General info that could be nice to send. e.g. on error, send why.
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <pre>
     * State of the chess game after the move sent has been made locally. i.e. what the board will look like.
     * </pre>
     *
     * <code>string board = 3;</code>
     */
    java.lang.String getBoard();
    /**
     * <pre>
     * State of the chess game after the move sent has been made locally. i.e. what the board will look like.
     * </pre>
     *
     * <code>string board = 3;</code>
     */
    com.google.protobuf.ByteString
        getBoardBytes();

    /**
     * <code>.ChessAction.Turn currentplayer = 4;</code>
     */
    int getCurrentplayerValue();
    /**
     * <code>.ChessAction.Turn currentplayer = 4;</code>
     */
    se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction.Turn getCurrentplayer();
  }
  /**
   * Protobuf type {@code ChessAction}
   */
  public  static final class ChessAction extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ChessAction)
      ChessActionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChessAction.newBuilder() to construct.
    private ChessAction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChessAction() {
      move_ = "";
      message_ = "";
      board_ = "";
      currentplayer_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChessAction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              move_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              board_ = s;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              currentplayer_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return se.kth.cnlib.protobuf.ChessActionOuterClass.internal_static_ChessAction_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return se.kth.cnlib.protobuf.ChessActionOuterClass.internal_static_ChessAction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction.class, se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction.Builder.class);
    }

    /**
     * <pre>
     * Whos turn after the sent move has been made.
     * </pre>
     *
     * Protobuf enum {@code ChessAction.Turn}
     */
    public enum Turn
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>WHITE = 0;</code>
       */
      WHITE(0),
      /**
       * <code>BLACK = 1;</code>
       */
      BLACK(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>WHITE = 0;</code>
       */
      public static final int WHITE_VALUE = 0;
      /**
       * <code>BLACK = 1;</code>
       */
      public static final int BLACK_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Turn valueOf(int value) {
        return forNumber(value);
      }

      public static Turn forNumber(int value) {
        switch (value) {
          case 0: return WHITE;
          case 1: return BLACK;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Turn>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Turn> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Turn>() {
              public Turn findValueByNumber(int number) {
                return Turn.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction.getDescriptor().getEnumTypes().get(0);
      }

      private static final Turn[] VALUES = values();

      public static Turn valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Turn(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ChessAction.Turn)
    }

    public static final int MOVE_FIELD_NUMBER = 1;
    private volatile java.lang.Object move_;
    /**
     * <pre>
     * Standard algebraic chess notation
     * </pre>
     *
     * <code>string move = 1;</code>
     */
    public java.lang.String getMove() {
      java.lang.Object ref = move_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        move_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Standard algebraic chess notation
     * </pre>
     *
     * <code>string move = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMoveBytes() {
      java.lang.Object ref = move_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        move_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object message_;
    /**
     * <pre>
     * General info that could be nice to send. e.g. on error, send why.
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * General info that could be nice to send. e.g. on error, send why.
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BOARD_FIELD_NUMBER = 3;
    private volatile java.lang.Object board_;
    /**
     * <pre>
     * State of the chess game after the move sent has been made locally. i.e. what the board will look like.
     * </pre>
     *
     * <code>string board = 3;</code>
     */
    public java.lang.String getBoard() {
      java.lang.Object ref = board_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        board_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * State of the chess game after the move sent has been made locally. i.e. what the board will look like.
     * </pre>
     *
     * <code>string board = 3;</code>
     */
    public com.google.protobuf.ByteString
        getBoardBytes() {
      java.lang.Object ref = board_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        board_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CURRENTPLAYER_FIELD_NUMBER = 4;
    private int currentplayer_;
    /**
     * <code>.ChessAction.Turn currentplayer = 4;</code>
     */
    public int getCurrentplayerValue() {
      return currentplayer_;
    }
    /**
     * <code>.ChessAction.Turn currentplayer = 4;</code>
     */
    public se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction.Turn getCurrentplayer() {
      se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction.Turn result = se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction.Turn.valueOf(currentplayer_);
      return result == null ? se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction.Turn.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMoveBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, move_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      if (!getBoardBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, board_);
      }
      if (currentplayer_ != se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction.Turn.WHITE.getNumber()) {
        output.writeEnum(4, currentplayer_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMoveBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, move_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      if (!getBoardBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, board_);
      }
      if (currentplayer_ != se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction.Turn.WHITE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, currentplayer_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction)) {
        return super.equals(obj);
      }
      se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction other = (se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction) obj;

      boolean result = true;
      result = result && getMove()
          .equals(other.getMove());
      result = result && getMessage()
          .equals(other.getMessage());
      result = result && getBoard()
          .equals(other.getBoard());
      result = result && currentplayer_ == other.currentplayer_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MOVE_FIELD_NUMBER;
      hash = (53 * hash) + getMove().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (37 * hash) + BOARD_FIELD_NUMBER;
      hash = (53 * hash) + getBoard().hashCode();
      hash = (37 * hash) + CURRENTPLAYER_FIELD_NUMBER;
      hash = (53 * hash) + currentplayer_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ChessAction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ChessAction)
        se.kth.cnlib.protobuf.ChessActionOuterClass.ChessActionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return se.kth.cnlib.protobuf.ChessActionOuterClass.internal_static_ChessAction_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return se.kth.cnlib.protobuf.ChessActionOuterClass.internal_static_ChessAction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction.class, se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction.Builder.class);
      }

      // Construct using se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        move_ = "";

        message_ = "";

        board_ = "";

        currentplayer_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return se.kth.cnlib.protobuf.ChessActionOuterClass.internal_static_ChessAction_descriptor;
      }

      public se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction getDefaultInstanceForType() {
        return se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction.getDefaultInstance();
      }

      public se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction build() {
        se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction buildPartial() {
        se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction result = new se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction(this);
        result.move_ = move_;
        result.message_ = message_;
        result.board_ = board_;
        result.currentplayer_ = currentplayer_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction) {
          return mergeFrom((se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction other) {
        if (other == se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction.getDefaultInstance()) return this;
        if (!other.getMove().isEmpty()) {
          move_ = other.move_;
          onChanged();
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        if (!other.getBoard().isEmpty()) {
          board_ = other.board_;
          onChanged();
        }
        if (other.currentplayer_ != 0) {
          setCurrentplayerValue(other.getCurrentplayerValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object move_ = "";
      /**
       * <pre>
       * Standard algebraic chess notation
       * </pre>
       *
       * <code>string move = 1;</code>
       */
      public java.lang.String getMove() {
        java.lang.Object ref = move_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          move_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Standard algebraic chess notation
       * </pre>
       *
       * <code>string move = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMoveBytes() {
        java.lang.Object ref = move_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          move_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Standard algebraic chess notation
       * </pre>
       *
       * <code>string move = 1;</code>
       */
      public Builder setMove(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        move_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Standard algebraic chess notation
       * </pre>
       *
       * <code>string move = 1;</code>
       */
      public Builder clearMove() {
        
        move_ = getDefaultInstance().getMove();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Standard algebraic chess notation
       * </pre>
       *
       * <code>string move = 1;</code>
       */
      public Builder setMoveBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        move_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <pre>
       * General info that could be nice to send. e.g. on error, send why.
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * General info that could be nice to send. e.g. on error, send why.
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * General info that could be nice to send. e.g. on error, send why.
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * General info that could be nice to send. e.g. on error, send why.
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * General info that could be nice to send. e.g. on error, send why.
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object board_ = "";
      /**
       * <pre>
       * State of the chess game after the move sent has been made locally. i.e. what the board will look like.
       * </pre>
       *
       * <code>string board = 3;</code>
       */
      public java.lang.String getBoard() {
        java.lang.Object ref = board_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          board_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * State of the chess game after the move sent has been made locally. i.e. what the board will look like.
       * </pre>
       *
       * <code>string board = 3;</code>
       */
      public com.google.protobuf.ByteString
          getBoardBytes() {
        java.lang.Object ref = board_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          board_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * State of the chess game after the move sent has been made locally. i.e. what the board will look like.
       * </pre>
       *
       * <code>string board = 3;</code>
       */
      public Builder setBoard(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        board_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * State of the chess game after the move sent has been made locally. i.e. what the board will look like.
       * </pre>
       *
       * <code>string board = 3;</code>
       */
      public Builder clearBoard() {
        
        board_ = getDefaultInstance().getBoard();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * State of the chess game after the move sent has been made locally. i.e. what the board will look like.
       * </pre>
       *
       * <code>string board = 3;</code>
       */
      public Builder setBoardBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        board_ = value;
        onChanged();
        return this;
      }

      private int currentplayer_ = 0;
      /**
       * <code>.ChessAction.Turn currentplayer = 4;</code>
       */
      public int getCurrentplayerValue() {
        return currentplayer_;
      }
      /**
       * <code>.ChessAction.Turn currentplayer = 4;</code>
       */
      public Builder setCurrentplayerValue(int value) {
        currentplayer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.ChessAction.Turn currentplayer = 4;</code>
       */
      public se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction.Turn getCurrentplayer() {
        se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction.Turn result = se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction.Turn.valueOf(currentplayer_);
        return result == null ? se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction.Turn.UNRECOGNIZED : result;
      }
      /**
       * <code>.ChessAction.Turn currentplayer = 4;</code>
       */
      public Builder setCurrentplayer(se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction.Turn value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        currentplayer_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ChessAction.Turn currentplayer = 4;</code>
       */
      public Builder clearCurrentplayer() {
        
        currentplayer_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ChessAction)
    }

    // @@protoc_insertion_point(class_scope:ChessAction)
    private static final se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction();
    }

    public static se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChessAction>
        PARSER = new com.google.protobuf.AbstractParser<ChessAction>() {
      public ChessAction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ChessAction(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChessAction> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChessAction> getParserForType() {
      return PARSER;
    }

    public se.kth.cnlib.protobuf.ChessActionOuterClass.ChessAction getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChessAction_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChessAction_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ChessAction.proto\"\203\001\n\013ChessAction\022\014\n\004m" +
      "ove\030\001 \001(\t\022\017\n\007message\030\002 \001(\t\022\r\n\005board\030\003 \001(" +
      "\t\022(\n\rcurrentplayer\030\004 \001(\0162\021.ChessAction.T" +
      "urn\"\034\n\004Turn\022\t\n\005WHITE\020\000\022\t\n\005BLACK\020\001B\027\n\025se." +
      "kth.cnlib.protobufb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ChessAction_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ChessAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChessAction_descriptor,
        new java.lang.String[] { "Move", "Message", "Board", "Currentplayer", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
